### ISSUE TITLE
Many SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by BeppeMc** [jive-vlbi/sched#10]
sched.py didn't run for many "SyntaxError: invalid syntax" in:
sched.py line31
version.py line 20
stmsg_module.py  at lines 19,20,27 and many others
plot_tool_bar.py at lines 131,137

Removing the letter "f" before each string solved the problem.

**Comment by bobeldering** [comment]
Hi Beppe,

Thanks for the report!

Those f-string are a new type of string formatting, introduced in python
version 3.6. I had assumed they were introduced in version 3, but
obviously that was a mistake. For now, I have release a bug fix version
of pySCHED that makes the requirement of python version 3.6 explicit
when installed with pip.

The idea of the f-string is that you can write the variables (or
expressions) to print directly in the string. While removing the f from
the string might make the program function, it will print the variable
names instead of their value. So the log output of pySCHED will not be
very informative.

Cheers,
Bob




>>> BeppeMc <notifications@github.com> 11/04/20 11:34 AM >>>

 sched.py didn't run for many "SyntaxError: invalid syntax" in:
 sched.py line31
 version.py line 20
 stmsg_module.py  at lines 19,20,27 and many others
 plot_tool_bar.py at lines 131,137
 Removing the letter "f" before each string solved the problem.

**Comment by BeppeMc** [comment]
Thanks Bob for clarification. I was not aware of that and I see that 
without them the program starts to work, for this reason I supposed a 
bug.
As python3 effectivly I have 3.5.3 version.

Cheers, Beppe.
