### ISSUE TITLE
Installation Issue with pySCHED

### ISSUE THREAD

**Issue by Tronadin** [jive-vlbi/sched#19]
Hi there,
I've been tasked to use pySCHED for some work i'm doing for University but i'm coming across some errors when trying;
sudo pip3 install pythonSCHED

I'm using a UBUNTU shell on VMWARE. I have pip3 installed as well as 1.22 Numpy but when I run the above script I get errors which I have attached as a Notepad.

Any help would be great.
[SCHED problem.txt](https://github.com/jive-vlbi/sched/files/7835875/SCHED.problem.txt)
Edit: Made more info available on the link

**Comment by bobeldering** [comment]
The error report you attached mentions that it cannot find a Fortran compiler. pySCHED's code is built on top of SCHED, which is a Fortran program. Part of that code base has to be compiled during the installation process. Since you are running Ubuntu, installing gfortran should do the trick:
sudo apt install gfortran

If some Fortran compiler is already installed on your system, but the setup script just cannot find it, please let us know which compiler you have installed.

**Comment by Tronadin** [comment]
oh great! It worked after installing gfortran. Thanks a bunch
