### ISSUE TITLE
Use 'tight' layout for plots by default

### ISSUE THREAD

**Issue by PE1NUT** [jive-vlbi/sched#8]
The current plots have a lot of whitespace around them. By clicking 'configure' in the graph window, it is possible to use the matplotlib 'tight' layout, which looks better. Proposal is to make this the default. Note that the button under configure is currently not a toggle, and does not seem to allow reverting back to the less tight layout at this moment. In the 'uptime plot', tight layout doesn't leave room for the key. Suggestion there is to print the station names at the end of each bar, so it becomes easier to match each graph to its station.

**Comment by bobeldering** [comment]
Handled in version 1.14:
-The tight layout is applied to all plots on creation.
-The legend in the uptime plot is now above the plot and is considered in the tight layout. Internal in matplotlib this layout is not a state, it is computed for the current configuration of the window. The reset button in the same window as the tight layout button will undo changes made (by clicking tight layout and otherwise).
